- text: will (at) willbadart (dot) com
  icon: envelope-o

- text: "@wbadart"
  icon: github
  link: github.com/wbadart

- text: "@wbadart"
  icon: stack-overflow
  link: stackoverflow.com/users/4025659/wbadart

- text: in/wbadart
  icon: linkedin
  link: linkedin.com/in/wbadart
